# Generated by Django 6.0 on 2025-12-09 20:52

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "title",
                    models.CharField(
                        help_text="Professional title/role", max_length=200
                    ),
                ),
                (
                    "bio",
                    ckeditor.fields.RichTextField(
                        help_text="Professional summary and background"
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        help_text="Your professional photo", upload_to="profile/"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        help_text="Upload CV/Resume PDF",
                        upload_to="resume/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Me",
                "verbose_name_plural": "About Me",
            },
        ),
        migrations.CreateModel(
            name="BombayShark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Bombay Sharks Football Academy", max_length=200
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        default="Founder | May 2025 - Present", max_length=300
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        help_text="Main academy photo", upload_to="bombay_sharks/"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Academy details and philosophy"
                    ),
                ),
                ("age_groups", models.CharField(default="U-6 to U-15", max_length=100)),
                (
                    "locations",
                    models.TextField(help_text="Operating locations across Mumbai"),
                ),
                (
                    "training_philosophy",
                    ckeditor.fields.RichTextField(
                        help_text="Training approach and methodology"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bombay Sharks Academy",
                "verbose_name_plural": "Bombay Sharks Academy",
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Certification name", max_length=300),
                ),
                ("issuing_organization", models.CharField(max_length=200)),
                ("issue_date", models.DateField()),
                ("credential_id", models.CharField(blank=True, max_length=100)),
                (
                    "certificate_image",
                    models.ImageField(
                        blank=True,
                        help_text="Certificate badge or image",
                        upload_to="certifications/",
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "ordering": ["-issue_date", "order"],
            },
        ),
        migrations.CreateModel(
            name="CompanyLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("logo", models.ImageField(upload_to="company_logos/")),
                (
                    "website_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                ("display_on_homepage", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Logo",
                "verbose_name_plural": "Company Logos",
                "ordering": ["order", "company_name"],
            },
        ),
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "interest_type",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("academy", "Academy Enrollment"),
                            ("both", "Both"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("U6", "Under 6"),
                            ("U8", "Under 8"),
                            ("U10", "Under 10"),
                            ("U12", "Under 12"),
                            ("U15", "Under 15"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                ("admin_notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Contact Submission",
                "verbose_name_plural": "Contact Submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if current position",
                        null=True,
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Job responsibilities and achievements"
                    ),
                ),
                (
                    "company_logo",
                    models.ImageField(blank=True, upload_to="experiences/"),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, help_text="Currently working here"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experiences",
                "ordering": ["-start_date", "order"],
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="bombay_sharks/gallery/")),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="portfolio.bombayshark",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
