# Generated by Django 6.0 on 2025-12-15 19:54

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(
                        help_text="High-quality action photo",
                        upload_to="action_photos/",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("coaching", "Coaching/Training"),
                            ("scouting", "Scouting/Analysis"),
                            ("event", "Event/Matchday"),
                            ("academy", "Bombay Sharks Academy"),
                            ("professional", "Professional Headshots"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("caption", models.TextField(blank=True, max_length=300)),
                ("featured_on_homepage", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Action Photo",
                "verbose_name_plural": "Action Photos",
                "ordering": ["order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., 'Revolutionizing Youth Scouting'",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-friendly version", unique=True),
                ),
                (
                    "subtitle",
                    models.CharField(
                        help_text="One-line impact summary", max_length=300
                    ),
                ),
                (
                    "problem",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="THE CHALLENGE - What problem did you solve?",
                    ),
                ),
                (
                    "solution",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="MY APPROACH - How did you solve it?"
                    ),
                ),
                (
                    "impact",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="THE IMPACT - Results with numbers/data"
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        help_text="Large header image for project",
                        upload_to="projects/",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated: Scouting, Analytics, Development",
                        max_length=200,
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(default=False, help_text="Show on homepage"),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Project / Case Study",
                "verbose_name_plural": "Projects / Case Studies",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Person's full name", max_length=200),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="e.g., 'Director of Football'", max_length=200
                    ),
                ),
                (
                    "company",
                    models.CharField(help_text="Organization name", max_length=200),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Professional headshot",
                        null=True,
                        upload_to="testimonials/",
                    ),
                ),
                (
                    "quote",
                    models.TextField(
                        help_text="Keep it short and impactful (2-3 sentences max)",
                        max_length=500,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        default=5,
                        help_text="1-5 star rating",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(default=False, help_text="Show on homepage"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower = first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Project gallery image", upload_to="projects/gallery/"
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Image",
                "verbose_name_plural": "Project Images",
                "ordering": ["order"],
            },
        ),
    ]
